name: 'Setup Inochi2D SDK'
run-name: 'Build Inochi2D Library (${{ inputs.variant }})...'

on:
  workflow_call:
    inputs:
      platform:
        required: true
        description: platform
        type: string
      tag:
        required: false
        description: 'Tag of SDK to fetch.'
        type: string
        default: 'latest'
      sdk:
        required: true
        description: 'Specific SDK to fetch.'
        type: string

permissions:
  contents: write

runs:
  using: "composite"
  steps:
    - name: 'Install ${{ inputs.sdk }} toolchain...'
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        wget https://github.com/Inochi2D/sdk-toolchain/releases/download/${{ inputs.tag }}/${{ inputs.sdk }}.tar.gz
        tar -xf ${{ inputs.sdk }}.tar.gz -C ${{ runner.tool_cache }}

    - name: 'Add ${{ inputs.sdk }} to PATH...'
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "${{ runner.tool_cache }}/ldc2/bin:${{ runner.tool_cache }}/ldc2/lib:$GITHUB_PATH" >> $GITHUB_PATH